// <auto-generated />
namespace Week_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class week1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(week1));
        
        string IMigrationMetadata.Id
        {
            get { return "202007051517357_week1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
